### ISSUE TITLE
Allow New database connection to be defined

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#12]
# Problem

The plugin currently supports connections already defined by PostGIS provider in QGIS. 

# Solution
Add support for allowing users to define a new connection in the plugin and make the available connection available for the PostGIS provider

**Comment by NyakudyaA** [comment]
Also linked to authentification framework that will be used.

**Comment by myarjunar** [comment]
Hi @NyakudyaA , I'll be adding new buttons to add new connection and refresh connection list for this, it would be something like this:

![database connection_065](https://cloud.githubusercontent.com/assets/11134669/25694864/e411bd80-30da-11e7-9e58-72f3b8aa14f9.png)

The add button will open `create new postgis connection` dialog.

**Comment by NyakudyaA** [comment]
Ok @myarjunar  that is okay.  Just make sure that when someone defines a new connection it can use all the values in the `postgis connection` with special mention of `service file`

**Comment by myarjunar** [comment]
> it can use all the values in the postgis connection with special mention of service file

hmm I don't really get it. But if it already covered by the postgres provider then it should be fine @NyakudyaA

**Comment by NyakudyaA** [comment]
@myarjunar  yes it should be covered by the postgres provider
