### ISSUE TITLE
Active connection should remember passwords

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#13]
# Problem
The plugin currently uses an already established postgis connection.  When you quit QGIS and restart QGIS the plugin still asks for a username and password.

![password](https://cloud.githubusercontent.com/assets/2510900/24505215/63227bca-1559-11e7-982b-e8c286e20297.png)

# Solution
Remember passwords and username for connections already defined.

**Comment by NyakudyaA** [comment]
If we use the QGIS authentication or PostGIS provider then this will be covered.

**Comment by myarjunar** [comment]
> If we use the QGIS authentication or PostGIS provider then this will be covered.

sure @NyakudyaA , but I think we still need to check the option to save username and password when we first create the pg connection.

**Comment by NyakudyaA** [comment]
Yes even when the password and username were saved that would still ask you about the password. I will test your PR

**Comment by myarjunar** [comment]
@NyakudyaA I haven't create a PR for this anyway :smiley:  but it will be there very soon

**Comment by NyakudyaA** [comment]
Does the PR #22 not cover it

**Comment by myarjunar** [comment]
no @NyakudyaA , it's in https://github.com/kartoza/parcel_plugin/pull/24
