### ISSUE TITLE
Add DDL scripts to create the database

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#16]
# Problem

We need to save DDL for creating tables and triggers as part of the plugin

# Solution

Port the current database with new materialised views as DDL

**Comment by NyakudyaA** [comment]
@gubuntu some of the tables are specific to Ogun state. Should we include them in the DDL. If we are creating the database for plugin specific, should we not just have specific tables and views which make the plugin work

**Comment by gubuntu** [comment]
we should have no location-specific tables or content. So, the schema probably needs a little review to make it generic. 

Also it must be able to handle any available CRS.

**Comment by gubuntu** [comment]
done and currently with #36
