### ISSUE TITLE
Add sample data sets and survey diagrams for Testing

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#17]
# Problem

Once the database has been created we need to cater for all loading the minimum sample data so that users can access the plugin functionality

# Solution
Prepare datasets from the existing database

**Comment by gubuntu** [comment]
I don't think sample data is needed for installation. Only for testing.

**Comment by timlinux** [comment]
Yup we need for tests - keep it really small and simple please.

**Comment by NyakudyaA** [comment]
Plugin has been tested in production and people are busy capturing parcels
