### ISSUE TITLE
publish in plugin repository

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#20]
- [x] Prepare and publish master in Kartoza QGIS plugin repo with  minimum needed for a user to start working with it (database init, docs etc.). Do this asap so client and others can test. 
  - https://github.com/kartoza/parcel_plugin/releases/tag/v2.1
- [ ] Once the updated version is released, update it on Kartoza repo or publish on official QGIS repo (make this call at the time)
  - pre-release v3.0

**Comment by NyakudyaA** [comment]
@cchristelis helped publish this in Kartoza repo. But the kartoza plugin repository had to be update. Will close this issue once the updates to the plugin repo have been pushed upstream

**Comment by NyakudyaA** [comment]
I have published master as version 2.0 and I can install it properly. Tested on a separate machine and it works well. Will leave the ticket open until we have pushed the updated version of the plugin repository

**Comment by gubuntu** [comment]
I've updated tags and made the current release v2.1. v2.0 was released in 2014.

**Comment by NyakudyaA** [comment]
I will close this as we already have a published plugin in the repo. Will publish version 3 as soon as the last feature is done
