### ISSUE TITLE
handle multiple CRSs and datums

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#26]
From discussion between @holysanta and @gubuntu on 23 March 2017 (not in original scope)
> There are two datums in use in Niger state. Can we handle these in the plugin? 

# Possible solutions
- Store both in database? 
- Or transform from QGIS into 4326 or geography.

**Comment by NyakudyaA** [comment]
We have taken the route of having two databases each one to use a specific CRS on launch.
