### ISSUE TITLE
Option to select the CRS

### ISSUE THREAD

**Issue by myarjunar** [kartoza/parcel_plugin#27]
# Problem

There is no option to select the CRS (UTM 31N or UTM32N in Niger State) during setup. We can't get past the initial point where we insert the principal beacon because surveys are mostly in UTM 32N.

# Proposed solution

- most basic: instruct the user to edit the database DDL to choose the correct SRID for all geometry and then use the matching one in QGIS. 
- easier for the user: give the user an option on setup (once-off) to choose the SRID

Later: add options for multiple CRSs per #26

**Comment by myarjunar** [comment]
I don't have any clues on this problem :grinning: , could you give me some explanation about this? @NyakudyaA

**Comment by NyakudyaA** [comment]
@myarjunar the area being surveyed is covered by two geographical zones with these different datums. So let say we have two tables. table_a and table_b representing (UTM 31N or UTM32N). So what they want is to say when you initialise the plugin choose which datum you are in and the corresponding data will be saved in the correct table with correct CRS. I think on the database dialog you can include an option to choose a CRS and have two choices (UTM 31N and UTM 32N)

**Comment by NyakudyaA** [comment]
Added the option and it's working well with a new database
