### ISSUE TITLE
Plugin doesn't load after first use

### ISSUE THREAD

**Issue by myarjunar** [kartoza/parcel_plugin#28]
Plugin doesn't load after first use. I have to restart QGIS to launch the plugin again.

**Comment by NyakudyaA** [comment]
@myarjunar I tried this and I think it is not a code issue. I think it has to do with the plugin repo that @dimasciput designed. Everything works well when I use my cloned repo but installing the plugin is a big issue and causing this error

**Comment by gubuntu** [comment]
It could also be that all the requirements that are present in the GH repo are not being packaged in the plugin. I would eliminate that possibility first

**Comment by NyakudyaA** [comment]
The plugin works properly. I have tested it extensively on my windows and ubuntu laptop.
