### ISSUE TITLE
cannot install or detect plugin

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#33]
I can download and 'install' the plugin from the Kartoza plugin repo but it immediately throws this error:
```
Plugin has disappeared:The plugin seems to have been installed but I don't know where. Probably the plugin package contained a wrong named directory. Please search the list of installed plugins. I'm nearly sure you'll find the plugin there, but I just can't determine which of them it is. It also means that I won't be able to determine if this plugin is installed and inform you about available updates. However the plugin may work. Please contact the plugin author and submit this issue.
```
The plugin directory is definitely in the right place after installing. 

Restarting QGIS does not fix. 

ALSO, if I make the plugin a soft link pointing to my checkout (instead of downloading it from the plugin repo), QGIS does not pick it up at all. 

QGIS 2.18.7 on OSX
QGIS 2.18.9 on Ubuntu 16.04

**Comment by ismailsunni** [comment]
I get the issue also for downloading the plugin from kartoza plugin repo.

> ALSO, if I make the plugin a soft link pointing to my checkout (instead of downloading it from the plugin repo), QGIS does not pick it up at all.

Is it the same problem that you mentioned in Jakarta? Did you use `ln` command and not use OSX alias ?
Can you try with another plugin ?

**Comment by gubuntu** [comment]
Yes I used ln on Mac and Ubuntu. 

And Cadasta from the Kartoza repo installs fine. 

@NyakudyaA @myarjunar did you upload a new zip file recently? Have init files or the dir structure changed? Pls fix urgently.

**Comment by NyakudyaA** [comment]
@gubuntu  @dimasciput  I have fixed this I think the main issue comes from the plugin repo which is causing this error. I will write a ticket and let @dimasciput  know and test.  @gubuntu  can you try to install now. You can close the ticket if it installs properly

**Comment by dimasciput** [comment]
Thanks @NyakudyaA , could you write the ticket in kartoza repo? Thank you.

**Comment by gubuntu** [comment]
there was also a problem in the GH repo itself. I can now install by downloading and via sof links on Mac and Ubuntu
