### ISSUE TITLE
clean up DDL

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#36]
- [ ] remove roles (it tries to make 'docker' owner, which doesn't exist). And 'deeds' with postgres owner prevents user from writing beacons. So owner must default to current user. 
- [x] It seems to be trying to create postgis and related extensions. Either make sure it does (just PostGIS itself, not topology or raster) or make it clear in the notes that the user must add PostGIS beforehand.
- [ ] It's also creating a nuch of other tables and there are Ogun names: it must be clean and generic and only create relations that are needed by the plugin
- [ ] The :CRS variable substitution does not work for function creation. Either get it to work or use another approach
It should't just be the sql dump form a production database....

**Comment by NyakudyaA** [comment]
Solved via f53694c.  Users will need to just create a database and the script will install PostGIS and create the necessary tables. The script still uses a variable which should be replaced in a text editor. Will edit the document to reflect this
