### ISSUE TITLE
change database connection

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#37]
In the original version (master) there is no way to change the database connection. 

If you want to work on another database there needs to be an easy way in the UI to change the connection. 

If it is to another database, then what?
- unload all layers and reload from new database?
- prompt user to save project and open a new project?

If it is just changing credentials that should be easier?

**Comment by NyakudyaA** [comment]
@gubuntu  There is now a new icon for managing database connections. This allows a user to create a new connection directly and also changing database connections.

![database](https://user-images.githubusercontent.com/2510900/26880763-c6f3edc4-4b95-11e7-9a6c-321d226be1f6.png)
The only logic that does not exists relates to managing layers already loaded when a new connection is choosen.

Another solution could be
* When a new connection is defined all layers loaded should be in a group layer. ie utm31n depending on the projection defined
* When a user decides to use another database the layers can be loaded into another group layer. ie utm32
This will allow a user to have multiple group layers(each in it's own CRS) in the same QGIS project

**Comment by NyakudyaA** [comment]
Database connection exists will close this. The only issue left is for allowing layers to be removed when a new database connection is chosen.
