### ISSUE TITLE
cannot create a beacon

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#39]
1. I clicked the beacon button before creating a database connection. So I went to create the connection then came back and clicked the button and nothing happened. After restarting QGIS the create beacon dialog came up. 
1. I captured the beacon fields and clicked Save and the dialog disappeared but nothing else happened and a beacon was not created. 
1. Thereafter, clicking on the beacon button did nothing again.
1. QGIS does not close properly after one if these situations. It crashes instead when you say Quit (on Mac).

All the above happends on master and develop except in develop the dialogs seem to come up again.

**Comment by NyakudyaA** [comment]
@gubuntu  see attached gif showing how it is working.  I have tried to do it in the order you have mentioned.
![edit-1](https://user-images.githubusercontent.com/2510900/26879778-a34d01b0-4b92-11e7-850f-d3fd7a750d24.gif)

**Comment by gubuntu** [comment]
@NyakudyaA did you start from scratch with a new database and run your DDL? 

Did the beacon save properly?

Could you create the rest of the beacons and construct a parcel and save it?

**Comment by NyakudyaA** [comment]
Yes, I have created beacons and saved them properly. Have also done the same on Tobi's machine. Logged in remotely via team viewer. We can close this ticket now.
![samples](https://user-images.githubusercontent.com/2510900/26930654-56e29796-4c5e-11e7-95ca-9f768823147b.png)

**Comment by gubuntu** [comment]
this is mainly dependent on #36 being fixed
