### ISSUE TITLE
Develop TDP Production (C of O) Template in QGIS Composer for Government Surveyor

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#4]
# Problem
We need to create a template for printing maps with the following information:
![img_20170502_105846](https://cloud.githubusercontent.com/assets/2510900/25615417/512472f0-2f37-11e7-8072-aa3fdff8ee16.jpg)

#Solution
Create template

**Comment by holysanta** [comment]
![img_20170502_105846](https://cloud.githubusercontent.com/assets/3856658/25613730/352ea918-2f27-11e7-805c-330601362059.jpg)

**Comment by holysanta** [comment]
Government Survey

**Comment by NyakudyaA** [comment]
Sample survey sheet provided:
![government_sruvey](https://cloud.githubusercontent.com/assets/2510900/26244493/23b0961c-3c90-11e7-8af2-0d3170c52b33.png)

**Comment by gubuntu** [comment]
looking good @NyakudyaA 

@holysanta?

**Comment by NyakudyaA** [comment]
![gov](https://user-images.githubusercontent.com/2510900/28066378-04dd30ca-663d-11e7-83f1-96080a152969.png)
Small tweaks based on style especially alignment of labels on opposite end of the line.
