### ISSUE TITLE
automate application of styles and templates

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#43]
When the plugin is installed, the correct styles must be added to each layer eigher by adding them to the database as default styles or by loading a default project. There is lots of symbology, field validation etc. that should be there automatically

It would be nice to have the composer templates available or loaded too.

**Comment by gubuntu** [comment]
This can wait for now - as long as the styles are available in a project in the repo and the user manual points out how to get them and recommends that they be used

**Comment by NyakudyaA** [comment]
@gubuntu since the database dump is a plain SQL dump we can dump the `layer_styles` as plain SQL and incorporate the SQL  into the main SQL file we use to create the database on startup. We have to set the `SET XML OPTION DOCUMENT;` in the SQL file. Will do this on my free time @ home

**Comment by NyakudyaA** [comment]
Lookup tables are loaded with the form validations
