### ISSUE TITLE
clean up QGIS projects

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#46]
The user should have a seamless, intuitive experience and only have to find and load one project and from there do all their work. 

- [x] ensure all layers exist in the database created by the DDL script
- [x] ensure the service file defines the connection to that database
- [x] ensure the projects fetch layers and tables ONLY from the main database (at the moment layers come from 'sml' and 'gis' databases.
- [x] save each of the custom composers as templates inside the repo and manage them as templates. 
- [x] clear out all projects but one, which must have all the layers and tables with the best styles
- [x] load all the templates into the remaining project

**Comment by NyakudyaA** [comment]
All is being managed in one project called print survey. Tested on multiple machines including production with Tobi
