### ISSUE TITLE
Improve Error handling

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#48]
# Problem

There are multiple errors that occur when using the plugin due to user error.

# Solution
We need to implement nice error handling and also have a help section for each icon so that users.

NB: This is an open ticket and should be implemented at a later stage when we decide to put the plugin in QGIS repository

**Comment by gubuntu** [comment]
If you know what these are, they should be documented in the user documentation in preparation for implementing in code.

**Comment by NyakudyaA** [comment]
# Problem
* When a user clicks on each of the icons for the plugin before selecting the database we get a python error.
* Even after selecting a database and with the correct tables in the database. Clicking on some icons like Bearings and Distances gives a python error because the tables are not yet populated with data. 

# Solution
* We need to give an informative message when the icon is not working.  Ie When the plugin loads into QGIS grey out all the other icons and leave the Database icon active.
* When the database is selected- allow the icons to be active except manage bearings and distance
8 Only activate Manage bearings and distance if the necessary tables have been populated

**Comment by NyakudyaA** [comment]
All these issues have been fixed with the dev version of the plugin.
