### ISSUE TITLE
DB support

### ISSUE THREAD

**Issue by gubuntu** [kartoza/parcel_plugin#52]
from @holysanta 

[00:55, 11/30/2017] Tobi Sowole: i get this error when i attempt to setup the db
[00:55, 11/30/2017] Tobi Sowole: ERROR:  syntax error at or near ":"
LINE 407:     the_geom geometry(Point,:CRS) NOT NULL,
                                      ^
SQL state: 42601
Character: 10221
[00:55, 11/30/2017] Tobi Sowole: Psadvise
[06:33, 11/30/2017] Tobi Sowole: Changed the crs....
[06:33, 11/30/2017] Tobi Sowole: Is it OK to have 2 dbs?
[06:33, 11/30/2017] Tobi Sowole: One for each crs?

**Comment by NyakudyaA** [comment]
@holysanta 
What version of the plugin are you running. If you are running the master version from the plugin repo then you need to setup the database first with the proper tables

* Create a database

* Open the sql for creating the database in a text editor. Substitute :CRS with your preferred CRS you need to use eg 26332

* Run the sql file against the database and the tables will be created.

* Open the plugin and start working


The second setup for  running the development version which has the database connection tool

* Create the database

* Open the database connection tool in QGIS and define the PG connection to the created database.

* Follow the instruction manual to proceed.

All the instructions are documented in the Google document. If something is not clear I encourage you to write tickets in https://github.com/kartoza/parcel_plugin/issues

**Comment by NyakudyaA** [comment]
You do not need to substitute the values in the SQL file manually. Use the plugin to setup the database tables. This will guide you accordingly
