### ISSUE TITLE
Error deleting beacon created via bearing & distance

### ISSUE THREAD

**Issue by holysanta** [kartoza/parcel_plugin#55]
An error has occurred while executing Python code: 

Exception: Backend database query failed! Error raised: cannot refresh materialized view "public.boundaries" concurrently HINT:  Create a unique index with no WHERE clause on one or more columns of the materialized view. CONTEXT:  SQL statement "REFRESH MATERIALIZED VIEW CONCURRENTLY boundaries" PL/pgSQL function boundaries_views() line 3 at SQL statement . 
Traceback (most recent call last):
  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 287, in manageBearDist
    BearDistManager(self.iface, self.db, self.requiredLayers)
  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 562, in __init__
    self.run()
  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\plugin.py", line 614, in run
    (elink[0][3],)
  File "C:/Users/TOBI/.qgis2/python/plugins\parcel_plugin\database.py", line 85, in query
    raise Exception('Backend database query failed!\nError raised: %s.' %(str(e),))
Exception: Backend database query failed!
Error raised: cannot refresh materialized view "public.boundaries" concurrently
HINT:  Create a unique index with no WHERE clause on one or more columns of the materialized view.
CONTEXT:  SQL statement "REFRESH MATERIALIZED VIEW CONCURRENTLY boundaries"
PL/pgSQL function boundaries_views() line 3 at SQL statement
.

**Comment by NyakudyaA** [comment]
@holysanta  this error is the same as #54 Can you see that you are using the correct sql file to create the database

**Comment by NyakudyaA** [comment]
develop has been merged into master and everything is working. Tested on Mac and Ubuntu
