### ISSUE TITLE
Edit Beacon via Bearing & Distance

### ISSUE THREAD

**Issue by holysanta** [kartoza/parcel_plugin#64]
Edit beacons created via bearing and distance gives ffg error:
1. Does not delete the beacon connected to the Reference Beacon 
2. Doesn't save edit changes effected to the coordinates etc.

Please see error in attached image
![edit_beacon_not_saving](https://user-images.githubusercontent.com/3856658/39351529-b7dba4d6-49f9-11e8-9362-518923a153c5.png)

NB: The implication is that the last two beacons cannot be edited or deleted.

**Comment by NyakudyaA** [comment]
@holysanta I think beacons defined by the bearing and distances tool should/are not editable by default. I can delete the link

**Comment by holysanta** [comment]
![2018-05-10 12_33_55-qgis 2 18 14 - 26332_beacon_not_permiting_update](https://user-images.githubusercontent.com/3856658/39869496-a2df6fc0-5455-11e8-81af-c62b2d945e3e.png)
.....still cant edit any beacon with Bearing & Distance...

**Comment by holysanta** [comment]
the Beacon should be updated and not treated as new entry.
