### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by josesevilla** [kartoza/parcel_plugin#68]
I have problems installing the parcel CoGo plugin in QGIS Girona 3.0. and also setting the repository as a plugins- source...

This is what I get installing from a downloaded zip file from your site:

No se pudo cargar el complemento 'parcel_plugin' debido a un error al llamar a su método classFactory()

ModuleNotFoundError: No module named 'plugin'

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/josesevilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\parcel_plugin\__init__.py", line 55, in classFactory
    from plugin import SMLSurveyor
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'plugin'

Versión de Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)]
Versión de QGIS: 3.0.3-Girona Girona, 8a899c8758

Ruta de Python:

    C:/Users/josesevilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
    C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
    C:/Users/josesevilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    C:/Users/josesevilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
    C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
    C:\Program Files\QGIS 3.0\bin\python36.zip
    C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
    C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
    C:\Program Files\QGIS 3.0\bin
    C:\PROGRA~1\QGIS3~1.0\apps\Python36
    C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
    C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32
    C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32\lib
    C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\Pythonwin
    C:/Users/josesevilla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
    C:\Users\josesevilla\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by NyakudyaA** [comment]
@josesevilla the port for QGIS 3 is not yet merged into the main repository. Please look at the pull request https://github.com/kartoza/parcel_plugin/pull/67 which has been done to port it to QGIS 3. There are just a few issues that need to be ironed out before we merge it. 
I will close this as soon as we have it merged

**Comment by josesevilla** [comment]
I am ok with that! Thankyou anyway.

**Comment by josesevilla** [comment]
@NyakudyaA I accidentally closed the issue. I will reopen it so that you can close and reopen when the pull is merged.

**Comment by NyakudyaA** [comment]
@josesevilla I will close this ticket as I have merged the PR. You can try out the develop branch in QGIS 3. I will upload the plugin shortly to the plugin repository
