### ISSUE TITLE
Missing layers in database

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/parcel_plugin#9]
# Problem

We seem to have lost some layers from the database with the current dump we have.

![missing_layers](https://cloud.githubusercontent.com/assets/2510900/24505250/82d50596-1559-11e7-9374-7378e659fb1c.png)

# Solution

Toby to provide a recent database dump with all layers working properly

**Comment by gubuntu** [comment]
@NyakudyaA if you need something from Tobi (@holysanta) you need to ask directly.

**Comment by NyakudyaA** [comment]
All layers have been incorporated. They were defined as SQL in the file `work.sql`
